name: weekly-refresh
on:
  # every Monday 05:00 UTC  (06:00 UK time)
  schedule:
    - cron: '0 5 * * 1'
  # adds a handy “Run workflow” button
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1  Check out your repo (pulls any LFS files too)
      - uses: actions/checkout@v4
        with:
          lfs: true

      # 2  Install Python
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3  Install your project’s libraries
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4  Run your build scripts
      - name: Build dashboard & CSV
        run: |
          python scripts/build_dashboard.py        # adjust to your files
          python scripts/build_csv.py              # adjust to your files

      # 5  Copy outputs into the docs/ folder
      - name: Move artefacts to docs/
        run: |
          mkdir -p docs
          cp data/output/hse_dashboard.html docs/index.html
          cp data/output/hse_convictions.csv docs/convictions.csv

      # 6  Commit the refreshed files back to the repo
      - name: Commit updated dashboard
        run: |
          git config user.name  github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add docs/*
          git add data/reference/*.parquet || true   # large files go via LFS
          git commit -m "data: weekly refresh" || echo "Nothing new to commit"
          git push
