# 3  Install libraries  (unchanged…)

# 4  Fetch all external datasets
- name: Fetch public datasets
  run: |
    python scripts/fetch_la_centroids.py
    python scripts/fetch_population.py
    python scripts/fetch_riddor.py
    python scripts/fetch_imd.py
    python scripts/fetch_companies.py
    python scripts/fetch_fatals.py

# 5  Build CSV + dashboard
- name: Build CSV + dashboard
  run: |
    python scripts/build_csv.py
    python scripts/build_dashboard.py
